### ISSUE TITLE
记一次使用Spark算子之用top求TopN遇到的问题 | Francis` Blog

### ISSUE THREAD

**Issue by francis-du** [francis-du/francis-du.github.io#3]
https://francisdu2.github.io/2019/04/04/%E8%AE%B0%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8Spark%E7%AE%97%E5%AD%90%E4%B9%8B%E7%94%A8top%E6%B1%82TopN%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98/#more

**Comment by francisdu2** [comment]
Test ok！
